### ISSUE TITLE
WARNING: Multiple instances of Three.js being imported. 

### ISSUE THREAD

**Issue by drcmda** [0beqz/screen-space-reflections#1]
i'm getting this console log 
WARNING: Multiple instances of Three.js being imported. 

these two should be peerDependencies, by depending on them the bundler will include two bundles for threejs.

```json
	"dependencies": {
		"postprocessing": "^6.28.0",
		"three": "^0.141.0"
	},
```

**Comment by 0beqz** [comment]
Oh I see, thanks for reporting. That should be resolved now.
