### ISSUE TITLE
heavy flicker in some scenes

### ISSUE THREAD

**Issue by drcmda** [0beqz/screen-space-reflections#2]
for example: https://codesandbox.io/s/threejs-journey-level-1-forked-84he6c?file=/src/App.js

btw, wonderful, wonderful project! thank you so much for open sourcing this!

**Comment by drcmda** [comment]
looking through the sources, i picked up this bit:

```jsx
    ssrPass.setSize(size.width, size.height)
    ssrPass.kawaseBlurPass.kernelSize = KernelSize.SMALL
    ssrPass.kawaseBlurPass.setSize(size.width, size.height)
```

specifically the last line, and the flicker is gone, but seems like a bug that composer.setSize or at least ssrPass.setSize doesn't do this automatically?

**Comment by 0beqz** [comment]
So you set the size of the kawaseBlurPass whenever the screen resizes for example. I don't update the size of the KawaseBlurPass when SSRPass.setSize() is called as it doesn't have to be the same size as the SSRPass and can be configured to be e.g. smaller. The flickering should come from its resolution being way too low I think.
Another option could be to automatically resize the KawaseBlurPass in the future and instead of blurWidth and blurHeight you could just give it a resolutionScale.

**Comment by drcmda** [comment]
i'll post the code since it shows how i divided it between setup, effects and updates:

```jsx
export const SSR = forwardRef<SSRPass, SSRProps>(function SSR(
  { blurSize = 512, enabled = true, ...props }: SSRProps,
  ref: Ref<SSRPass>
) {
  const { size, viewport, invalidate } = useThree()
  const { composer, scene, camera } = useContext(EffectComposerContext)

  const [options] = useState({
    width: size.width,
    height: size.height,
    blurWidth: blurSize,
    blurHeight: blurSize,
    blurKernelSize: KernelSize.SMALL,
    rayStep: 0.1,
    intensity: 1,
    power: 1,
    depthBlur: 0.1,
    enableJittering: false,
    jitter: 0.1,
    jitterSpread: 0.1,
    roughnessFadeOut: 1,
    MAX_STEPS: 20,
    NUM_BINARY_SEARCH_STEPS: 5,
    maxDepthDifference: 1,
    maxDepth: 1,
    thickness: 10,
    ior: 1.45,
    useBlur: true,
    useMRT: true,
    useNormalMap: true,
    useRoughnessMap: true,
    ...props,
  })

  const [pass] = useState(() => new SSRPass(composer, scene, camera, options))

  useEffect(() => {
    Object.keys(props).forEach(
      (key) => pass.reflectionUniforms[key] && (pass.reflectionUniforms[key].value = props[key])
    )
  }, [props])

  useEffect(() => {
    // Steps
    pass.reflectionsPass.fullscreenMaterial.defines.MAX_STEPS = Math.ceil(props.MAX_STEPS)
    pass.reflectionsPass.fullscreenMaterial.defines.NUM_BINARY_SEARCH_STEPS = Math.ceil(props.NUM_BINARY_SEARCH_STEPS)

    // Blur
    if (props.useBlur) {
      pass.fullscreenMaterial.defines.USE_BLUR = ''
      pass.reflectionsPass.fullscreenMaterial.defines.USE_BLUR = ''
    } else {
      delete pass.fullscreenMaterial.defines.USE_BLUR
      delete pass.reflectionsPass.fullscreenMaterial.defines.USE_BLUR
    }

    // Jitter
    if (props.enableJittering) {
      pass.reflectionsPass.fullscreenMaterial.defines.USE_JITTERING = ''
    } else {
      delete pass.reflectionsPass.fullscreenMaterial.defines.USE_JITTERING
    }

    // Enabled
    pass.fullscreenMaterial.defines.RENDER_MODE = enabled ? 0 : 4

    // Update materials
    pass.reflectionsPass.fullscreenMaterial.needsUpdate = true
    pass.fullscreenMaterial.needsUpdate = true
  }, [enabled, props.useBlur, props.enableJittering, props.NUM_BINARY_SEARCH_STEPS, props.MAX_STEPS])

  useEffect(() => {
    pass.setSize(size.width * viewport.dpr, size.height * viewport.dpr)
    pass.kawaseBlurPass.setSize(blurSize, blurSize)
    invalidate()
  }, [blurSize, size, viewport, composer, pass, invalidate])

  useLayoutEffect(() => {
    composer.addPass(pass)
    return () => {
      composer.removePass(pass)
    }
  }, [composer, pass])

  return null
})
```

what made it work in the end was just `pass.kawaseBlurPass.setSize(blurSize, blurSize)`. even if blur was ticked off, kawaseBlurPass with untouched default settings led to crazy flicker but giving it any value made it OK.

**Comment by drcmda** [comment]
two things i still haven't figured out:

1. composer.dispose() caused an infinite loop, i think i should call it in effect clean-up.
2. pass.setSize(size.width * viewport.dpr, size.height * viewport.dpr) felt odd, size is the canvas size in pixels, but without multiplying it by the pixelratio the noise is considerably more grainy.

**Comment by 0beqz** [comment]
Regarding 1: that should be fixed by PR https://github.com/0beqz/screen-space-reflections/pull/3. It's because postprocessing.js is recursively calling dispose() on the `composer` class variable from the SSRPass.

2: Not too sure about that but I can take dpr into account when resizing in the future if you call composer.setSize()
