### ISSUE TITLE
request: allow ssr for selected meshes

### ISSUE THREAD

**Issue by drcmda** [0beqz/screen-space-reflections#4]
similar to outlines and bloom in postprocessing: https://github.com/pmndrs/postprocessing/blob/main/src/core/Selection.js this could allow us to mix and match, place it on certain regions and perhaps achieve a cleaner look while improving performance? in sketchfab they have something similar where ssr is usually being using on metallic surfaces.

**Comment by 0beqz** [comment]
I can definitely add that. Selective reflections will definitely improve performance. So these selected objects shouldn't reflect anything but can still be reflections or should they be excluded entirely so that they don't reflect anything and also will never be visible regarding reflections. I could add both options.

**Comment by drcmda** [comment]
from how outlines work, the selected meshes will have the effect: https://codesandbox.io/s/selective-outlines-d36mw it's been a while since i used the vanilla api since it was abstracted into the `<Select>` component a while ago, but it would the same way i guess. so if i had a car and i want only the bumper to reflect, i'd select it, everything else remains untouched, but the bumper will have the surrounding reflected.

**Comment by 0beqz** [comment]
Ah I see, I'll check how it's done in postprocessing.js and will implement it similar to it

**Comment by optimus007** [comment]
![err](https://user-images.githubusercontent.com/6885294/177154708-366cc83e-0e36-40be-98f6-a1c5226a4cff.png)
![err1](https://user-images.githubusercontent.com/6885294/177154717-8012d1ce-e5d6-41f0-8f80-fb3c6eefaa6f.png)

i'm guessing this would solve the problem i'm getting ?

**Comment by Ben-Mack** [comment]
+1 for this, it'll improve performance greatly on large scene.

**Comment by 0beqz** [comment]
> ![err](https://user-images.githubusercontent.com/6885294/177154708-366cc83e-0e36-40be-98f6-a1c5226a4cff.png) ![err1](https://user-images.githubusercontent.com/6885294/177154717-8012d1ce-e5d6-41f0-8f80-fb3c6eefaa6f.png)
> 
> i'm guessing this would solve the problem i'm getting immediately when composer is turned on ?

That shouldn't happen in the first place, I'm not sure what's causing that. Can you tell me which line in the SSRPass (or better from ReflectionPass) this error is coming from?

**Comment by optimus007** [comment]
@0beqz there's no error in the reflection , SSR and Render pass it's just the line which calls the render function which it last went went through before the error but this error only comes when using SSR + pmndrs composer

can you try adding a transform controls in the scene and try ?

i tried on 1.0.8 same error 

SSR initialized like this (other passes like bloom ssao brightness cont works fine)
```
  const ssrEffect = new SSRPass(scene, camera);
  composer.addPass(ssrEffect)
```

**Comment by 0beqz** [comment]
> @0beqz there's no error in the reflection , SSR and Render pass it's just the line which calls the render function which it last went went through before the error but this error only comes when using SSR + pmndrs composer
> 
> can you try adding a transform controls in the scene and try ?
> 
> i tried on 1.0.8 and three js 142 same error
> 
> SSR initialized like this (other passes like bloom ssao brightness cont works fine)
> 
> ```
>   const ssrEffect = new SSRPass(scene, camera);
>   composer.addPass(ssrEffect)
> ```

Alright, so the transform controls seem to be causing that, I'll try to check what could be the issue behind that.

**Comment by optimus007** [comment]
![no-tcon](https://user-images.githubusercontent.com/6885294/180377876-f7b39d14-78a3-48b9-9d5d-c4984588122e.png)
![tcon added](https://user-images.githubusercontent.com/6885294/180377882-ae821d2f-3f3d-41ad-9e40-36968720b7e4.png)

Checked on an bare bones scene to better isolate the issue (was using scissor test and other stuff before and just wanted to confirm ), and can confiem , just adding transformcontrols into the scene will result in this error

**Comment by 0beqz** [comment]
Alright sure, make a new issue. I'm wondering in which line from `ReflectionsPass` this error emerges from.
Could you test if you are also getting this error in the [example scene](https://github.com/0beqz/screen-space-reflections/tree/main/example) of this repository? I wasn't able to replicate that error when I used TransformControls in that scene - so adding it to the scene didn't seem to cause any issues there.

**Comment by 0beqz** [comment]
You can now use the SSREffect's `selection` property to set which meshes should reflect. Leaving it empty will make all meshes reflect.
